config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'municipes#index'

  resources :municipes, except: %i[show destroy]
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :municipe

  validates :zipcode, :street, :neighborhood, :city, :uf, presence: true

  validates :zipcode, format: { with: /\A\d{5}-\d{3}\z/ }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/searchable.rb
# frozen_string_literal: true

module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
  end
end

app/models/municipe.rb
# frozen_string_literal: true

class Municipe < ApplicationRecord
  include Searchable

  enum status: { active: 'active', inactive: 'inactive' }

  has_one :address, dependent: :destroy, inverse_of: :municipe

  has_one_attached :picture

  accepts_nested_attributes_for :address, allow_destroy: true, reject_if: :all_blank

  validates :full_name, :cpf, :cns, :email, :birthdate, :phone, :picture, presence: true
  validates :cpf, :cns, :email, uniqueness: { case_sensitive: false }
  validates :cpf, cpf: true, format: { with: /\A\d{3}\.\d{3}\.\d{3}-\d{2}\z/ }
  validates :cns, '::CnsBrazil::Cns': true
  validates :full_name, :email, length: { maximum: 255 }
  validates :phone, format: { with: /\A\+55\s\(\d{2}\)\s\d{5}-\d{4}\z/ }
  validates :birthdate, date: { before_or_equal_to: proc { Time.zone.now }, message: :invalid }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  after_commit :notify_welcome, on: :create
  after_commit :notify_updated, on: :update

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :full_name, type: :text
      indexes :cpf, type: :text
      indexes :cns, type: :text
      indexes :email, type: :text
    end
  end

  # exclui o campo picture para nao ser indexado
  def as_indexed_json(_options = {})
    as_json(
      except: [:picture]
    )
  end

  def notify_welcome
    sms_message = I18n.t('sms.messages.welcome')

    MunicipeMailer.welcome(self).deliver_later
    SmsService.new(phone, sms_message).send_sms unless Rails.env.test?
  end

  def notify_updated
    sms_message = I18n.t('sms.messages.updated')

    MunicipeMailer.updated(self).deliver_later
    SmsService.new(phone, sms_message).send_sms unless Rails.env.test?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ActiveStorageServiceHandler
end

app/controllers/concerns/active_storage_service_handler.rb
# frozen_string_literal: true

module ActiveStorageServiceHandler
  extend ActiveSupport::Concern

  included do
    before_action :set_active_storage_host

    def set_active_storage_host
      storage_service = Rails.application.config.active_storage.service
      return if storage_service == :amazon

      ActiveStorage::Current.url_options = {
        protocol: request.protocol,
        host: request.host,
        port: request.port
      }
    end
  end
end

app/controllers/municipes_controller.rb
# frozen_string_literal: true

class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[edit update]

  def index
    @municipes = if params[:search].present?
                   Municipe.search(params[:search]).records
                 else
                   Municipe.all
                 end
  end

  def new
    @municipe = Municipe.new
    @municipe.build_address
  end

  def edit
    @municipe.build_address unless @municipe.address
  end

  def create
    @municipe = Municipe.new(municipe_params)

    respond_to do |format|
      if @municipe.save
        format.html do
          redirect_to municipes_url, notice: t('resources.messages.created', resource: Municipe.model_name.human)
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @municipe.update(municipe_params)
        format.html do
          redirect_to municipes_url, notice: t('resources.messages.updated', resource: Municipe.model_name.human)
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_municipe
    @municipe = Municipe.find(params[:id])
  end

  def municipe_params
    params.require(:municipe).permit(:full_name, :cpf, :cns, :email, :birthdate, :phone, :picture, :status,
      address_attributes: %i[street zipcode complement neighborhood city uf ibge_code])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/municipes_helper.rb
# frozen_string_literal: true

module MunicipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Municipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/municipes/_address.html.erb
<h1 class="text-2xl font-bold text-gray-700">Endereço</h1>
<div id="address" >
  <div class="my-5">
    <div class="flex justify-between">
      <div class="w-1/4">
        <%= form.label :zipcode %>
        <%= form.text_field :zipcode, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full",
                            data: { action: "keyup->municipe-form#onZipCodeChange", "municipe-form-target": "zipcode"} %>
      </div>

      <div class="w-full">
        <%= form.label :street %>
        <%= form.text_field :street, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full",
                            data: { target: "municipe-form.street" } %>
      </div>
    </div>
  </div>

  <div class="my-5">
    <%= form.label :complement %>
    <%= form.text_field :complement, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <div class="flex justify-between">
      <div class="w-1/4">
        <%= form.label :neighborhood %>
        <%= form.text_field :neighborhood, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { target: "municipe-form.neighborhood" } %>
      </div>

      <div class="w-1/4 px-2">
        <%= form.label :city %>
        <%= form.text_field :city, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { target: "municipe-form.city" } %>
      </div>

      <div class="w-1/4 px-2">
        <%= form.label :uf %>
        <%= form.text_field :uf, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { target: "municipe-form.uf" } %>
      </div>

      <div class="w-1/4 px-2">
        <%= form.label :ibge_code %>
        <%= form.text_field :ibge_code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
    </div>
  </div>
</div>

app/views/municipes/_form.html.erb
<%= form_with(model: municipe, class: "contents", controller: 'municipe-form') do |form| %>
  <% if municipe.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(municipe.errors.count, "error") %> prohibited this municipe from being saved:</h2>

      <ul>
        <% municipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="municipe-form" data-controller="municipe-form">
    <div class="my-5">
      <%= form.label :full_name %>
      <%= form.text_field :full_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <div class="flex justify-between">
        <div class="w-1/3">
          <%= form.label :cpf %>
          <%= form.text_field :cpf, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full",
                              data: { "municipe-form-target": "cpf" } %>
        </div>

        <div class="w-1/3 px-2">
          <%= form.label :cns %>
          <%= form.text_field :cns, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>

        <div class="w-1/3">
          <%= form.label :birthdate %>
          <%= form.date_field :birthdate, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>
      </div>
    </div>

    <div class="my-5">
      <%= form.label :picture %>
      <%= form.file_field :picture, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <div class="flex justify-between">
        <div class="w-1/3">
          <%= form.label :phone %>
          <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full",
                              data: { "municipe-form-target": 'phone' } %>
        </div>

        <div class="w-1/3 px-2">
          <%= form.label :email %>
          <%= form.email_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>

        <div class="w-1/3">
          <%= form.label :status %>
          <%= form.select :status, options_for_select(t('activerecord.municipe.status').map { |i| [i.last, i.first] }, form.object.status),
                          { include_blank: true }, class: 'form-select block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
        </div>
      </div>
    </div>

    <div class="my-5">
      <%= form.fields_for :address, form.object.address do |address_form| %>
        <%= render 'address', form: address_form %>
      <% end %>
    </div>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/municipes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="flex justify-between">
    <h1 class="font-bold text-4xl"><%= t('actions.edit', model: Municipe.name.humanize) %></h1>

    <% if @municipe.picture.present? %>
      <%= image_tag @municipe.picture.url, class: "rounded-full", style: "max-width: 100px; max-height: 100px;" %>
    <% end %>
  </div>

  <%= render "form", municipe: @municipe %>

  <%= link_to t('helpers.subtitles.back'), municipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/municipes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center my-5">
    <%= link_to municipes_path do %>
      <h1 class="font-bold text-4xl"><%= Municipe.name.pluralize %></h1>
    <% end %>

    <%= form_with url: municipes_path, method: :get, local: true, class: "mt-8" do |form| %>
      <div class="flex justify-between">
        <%= form.text_field :search, value: params[:search], class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 mr-2" %>
        <%= form.submit t('helpers.subtitles.search'), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium ml-2" %>
      </div>
    <% end %>


    <%= link_to t('actions.create', model: Municipe.model_name.human), new_municipe_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="municipes" class="min-w-full">

    <table class="min-w-full table-auto">
      <thead>
      <tr>
        <th class="px-6 py-3 bg-gray-100 text-center font-medium"><%= Municipe.human_attribute_name :picture %></th>
        <th class="px-6 py-3 bg-gray-100 text-center font-medium"><%= Municipe.human_attribute_name :full_name %></th>
        <th class="px-6 py-3 bg-gray-100 text-center font-medium"><%= Municipe.human_attribute_name :cpf %></th>
        <th class="px-6 py-3 bg-gray-100 text-center font-medium"><%= Municipe.human_attribute_name :cns %></th>
        <th class="px-6 py-3 bg-gray-100 text-center font-medium"><%= Municipe.human_attribute_name :birthdate %></th>
        <th class="px-6 py-3 bg-gray-100 text-center font-medium"><%= Municipe.human_attribute_name :email %></th>
        <th class="px-6 py-3 bg-gray-100 text-center font-medium"><%= Municipe.human_attribute_name :phone %></th>
        <th class="px-6 py-3 bg-gray-100 text-center font-medium"><%= Municipe.human_attribute_name :status %></th>
        <th class="px-6 py-3 bg-gray-100"><%= I18n.t('helpers.subtitles.action') %></th>
      </tr>
      </thead>
      <tbody>
      <% @municipes.each do |municipe| %>
        <tr id="<%= dom_id municipe %>" style="text-align: center">
          <td class="px-6 py-4">
            <% if municipe.picture.present? %>
              <%= image_tag municipe.picture.url, class: "rounded-full", style: "max-width: 100px; max-height: 100px;" %>
            <% else %>
              <%= image_tag "default_picture.jpg", class: "rounded-full", style: "max-width: 100px; max-height: 100px;" %>
            <% end %>
          </td>
          <td class="px-6 py-4"><%= municipe.full_name %></td>
          <td class="px-6 py-4"><%= municipe.cpf %></td>
          <td class="px-6 py-4"><%= municipe.cns %></td>
          <td class="px-6 py-4"><%= l municipe.birthdate %></td>
          <td class="px-6 py-4"><%= municipe.email %></td>
          <td class="px-6 py-4"><%= municipe.phone %></td>
          <td class="px-6 py-4"><%= t("activerecord.municipe.status.#{municipe.status}") %></td>
          <td class="px-6 py-4">
            <% if action_name != "show" %>
              <%= link_to t('helpers.subtitles.edit'), edit_municipe_path(municipe), class: "rounded-lg py-2 px-4 ml-2 bg-gray-100 inline-block font-medium" %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/municipes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= t('actions.new', model: Municipe.model_name.human) %></h1>

  <%= render "form", municipe: @municipe %>

  <%= link_to t('helpers.subtitles.back'), municipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>